name: Update Bandit Progress Badge
on:
  push:
    branches:
      - main
jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      
      - name: Count completed levels
        run: |
          # Count lines in BANDIT.md where Password is filled
          DONE=$(grep -E "Password:\s+\S+" BANDIT.md | wc -l)
          TOTAL=34
          echo "DONE=$DONE" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "Completed levels: $DONE out of $TOTAL"
      
      - name: Update README badge
        run: |
          BADGE="![Progress](https://img.shields.io/badge/Bandit%20Progress-${DONE}%2F${TOTAL}-brightgreen)"
          
          # Replace first line with badge; create README.md if it doesn't exist
          if [ ! -f README.md ]; then
            echo "$BADGE" > README.md
          else
            sed -i "1s|.*|$BADGE|" README.md
          fi
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update progress badge to ${{ env.DONE }}/${{ env.TOTAL }}"
          file_pattern: README.md
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          
