name: Update Bandit Progress Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count completed levels
        run: |
          # Count lines in BANDIT.md where Password is filled
          DONE=$(grep -E "Password:\s+\S+" BANDIT.md | wc -l)
          echo "DONE=$DONE" >> $GITHUB_ENV
          echo "Completed levels: $DONE"

      - name: Update README badge
        run: |
          TOTAL=34
          BADGE="![Progress](https://img.shields.io/badge/Bandit%20Progress-${DONE}%2F${TOTAL}-brightgreen)"
          
          # Replace first line with badge; create README.md if it doesn't exist
          if [ ! -f README.md ]; then
            echo "$BADGE" > README.md
          else
            sed -i "1s|.*|$BADGE|" README.md
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update progress badge to $DONE/$TOTAL" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
